apiVersion: apps/v1
kind: Deployment
metadata:
  name: sndai
  labels:
    app: sndai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sndai
  template:
    metadata:
      labels:
        app: sndai
    spec:
      containers:
        - name: app
          image: your-registry/sndai:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: "production"
            - name: MODEL_PROVIDER
              value: "openai"   # or "ollama"
            - name: DISCORD_ENABLED
              value: "true"     # set "false" to disable Discord bot
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sndai-secrets
                  key: OPENAI_API_KEY
            - name: BRAVE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sndai-secrets
                  key: BRAVE_API_KEY
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sndai-secrets
                  key: DISCORD_BOT_TOKEN
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sndai-secrets
                  key: DISCORD_CLIENT_ID
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: data
              mountPath: /app
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sndai-pvc
